# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@c22a5debd482401472b285de4f6deedf70ddbb92 # master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create issue
        id: create
        uses: atlassian/gajira-create@1c54357fdde9dab6273a0e26d67cb175ffffe498 # master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: |
            [SDK - experiment-python-server] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.html_url }}
          fields: '{
            "labels": ["experiment-python-server", "sdk-backlog-grooming", "github"]
          }'

      - name: Log created issue
        run: echo "Issue SKY-${{ steps.create.outputs.issue }} was created"
