name: Unit Test on Arm
on: [pull_request]

jobs:
  aarch_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7" ]
    name: Build on ubuntu aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit Test
        run: python -m unittest discover -s ./tests -p '*_test.py'
