name: Unit Test on Arm
on: [pull_request]

jobs:
  aarch_job:
    runs-on: ubuntu-latest
    environment: Unit Test
    name: Test on Ubuntu aarch64
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up and run unit test on aarch64
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          env: |
            API_KEY: ${{ secrets.API_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            EU_API_KEY: ${{ secrets.EU_API_KEY }}
            EU_SECRET_KEY: ${{ secrets.EU_SECRET_KEY }}
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            apt update
            apt -y install python3
            apt -y install pip
            apt -y install ca-certificates
          run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            python3 -m unittest discover -s ./tests -p '*_test.py'
