name: Unit Test on Arm
on: [pull_request]

jobs:
  aarch_job:
    runs-on: ubuntu-latest
    name: Test on ubuntu aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run Unit Test
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            apt update
            apt -y install python3
            apt -y install pip
            apt -y install ca-certificates
          run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            python3 -m unittest discover -s ./tests -p '*_test.py'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EU_API_KEY: ${{ secrets.EU_API_KEY }}
          EU_SECRET_KEY: ${{ secrets.EU_SECRET_KEY }}
